require 'rails_helper'
# require "spec_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe GlucoseLevelsController, type: :controller do

  before do
    @user = create(:user)
    sign_in @user
  end

  after do
    @user = nil
  end

  # This should return the minimal set of attributes required to create a valid
  # GlucoseLevel. As you add validations to GlucoseLevel, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    build(:glucose_level, user: @user).attributes.symbolize_keys
  }

  let(:invalid_attributes) {
    build(:user).attributes.symbolize_keys
  }

  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GlucoseLevelsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  

  describe "GET #index" do
    it "renders the index template" do
      get :index
      expect(response).to render_template("index")
    end

    it "returns a success response" do
      GlucoseLevel.create valid_attributes
      get :index, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #new" do
    it "returns a success response" do
      get :new, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new GlucoseLevel" do
        expect {
          post :create, params: {glucose_level: valid_attributes}, session: valid_session
        }.to change(GlucoseLevel, :count).by(1)
      end

      it "redirects to the glucose_levels path after create" do
        post :create, params: {glucose_level: valid_attributes}, session: valid_session
        expect(response).to redirect_to(glucose_levels_url)
      end
    end

    context "with invalid params" do
      let(:new_attributes) {{ value: nil, user: @user}}

      it "returns a success response" do
        post :create, params: {glucose_level: new_attributes}, session: valid_session
        expect(response).to be_successful
      end
    end
  end
end
